### ISSUE TITLE
macOS (Sierra) results

### ISSUE THREAD

**Issue by Hack5190** [karek314/macOS-home-call-drop#2]
Below are the results from running your script (bash ./homecall.sh fixmacos) on a 'fresh' macOS v0.12.2 (16C67) install.

With 1 exception (_com.apple.parsecd.plist_) it seems that none of the service files exist.

Hopefully the spotlight fixes worked.

---> Begin Cut & Paste <---

System Spotlight & Suggestions Fixed

/System/Library/LaunchAgents/com.apple.cloudfamilyrestrictionsd-mac.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.cloudfamilyrestrictionsd-mac.plist: Could not find specified service
Agent com.apple.cloudfamilyrestrictionsd-mac disabled
/System/Library/LaunchAgents/com.apple.cloudpaird.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.cloudpaird.plist: Could not find specified service
Agent com.apple.cloudpaird disabled
/System/Library/LaunchAgents/com.apple.cloudphotosd.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.cloudphotosd.plist: Could not find specified service
Agent com.apple.cloudphotosd disabled
/System/Library/LaunchAgents/com.apple.DictationIM.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.DictationIM.plist: Could not find specified service
Agent com.apple.DictationIM disabled
/System/Library/LaunchAgents/com.apple.assistant_service.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.assistant_service.plist: Could not find specified service
Agent com.apple.assistant_service disabled
/System/Library/LaunchAgents/com.apple.appleseed.seedusaged.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.appleseed.seedusaged.plist: Could not find specified service
Agent com.apple.appleseed.seedusaged disabled
/System/Library/LaunchAgents/com.apple.parentalcontrols.check.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.parentalcontrols.check.plist: Could not find specified service
Agent com.apple.parentalcontrols.check disabled
/System/Library/LaunchAgents/com.apple.parsecd.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.parsecd.plist: Operation not permitted while System Integrity Protection is engaged
Agent com.apple.parsecd disabled
/System/Library/LaunchAgents/com.apple.rtcreportingd.plist: No such file or directory
/System/Library/LaunchAgents/com.apple.rtcreportingd.plist: No such file or directory
Agent com.apple.rtcreportingd disabled
/System/Library/LaunchAgents/com.apple.SafariCloudHistoryPushAgent.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.SafariCloudHistoryPushAgent.plist: Could not find specified service
Agent com.apple.SafariCloudHistoryPushAgent disabled
/System/Library/LaunchAgents/com.apple.safaridavclient.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.safaridavclient.plist: Could not find specified service
Agent com.apple.safaridavclient disabled
/System/Library/LaunchAgents/com.apple.SafariNotificationAgent.plist: Could not find specified service
/System/Library/LaunchAgents/com.apple.SafariNotificationAgent.plist: Could not find specified service
Agent com.apple.SafariNotificationAgent disabled

Specified agents has been disabled

/System/Library/LaunchDaemons/com.apple.netbiosd.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.netbiosd.plist: Could not find specified service
Daemon com.apple.netbiosd disabled
/System/Library/LaunchDaemons/com.apple.familycontrols.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.familycontrols.plist: Could not find specified service
Daemon com.apple.familycontrols disabled
/System/Library/LaunchDaemons/com.apple.SubmitDiagInfo.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.SubmitDiagInfo.plist: Could not find specified service
Daemon com.apple.SubmitDiagInfo disabled
/System/Library/LaunchDaemons/com.apple.screensharing.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.screensharing.plist: Could not find specified service
Daemon com.apple.screensharing disabled
/System/Library/LaunchDaemons/com.apple.appleseed.fbahelperd.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.appleseed.fbahelperd.plist: Could not find specified service
Daemon com.apple.appleseed.fbahelperd disabled
/System/Library/LaunchDaemons/com.apple.AOSNotificationOSX.plist: No such file or directory
/System/Library/LaunchDaemons/com.apple.AOSNotificationOSX.plist: No such file or directory
Daemon com.apple.AOSNotificationOSX disabled
/System/Library/LaunchDaemons/com.apple.awacsd.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.awacsd.plist: Could not find specified service
Daemon com.apple.awacsd disabled
/System/Library/LaunchDaemons/com.apple.awdd.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.awdd.plist: Could not find specified service
Daemon com.apple.awdd disabled
/System/Library/LaunchDaemons/com.apple.CrashReporterSupportHelper.plist: Could not find specified service
/System/Library/LaunchDaemons/com.apple.CrashReporterSupportHelper.plist: Could not find specified service
Daemon com.apple.CrashReporterSupportHelper disabled

Specified daemons has been disabled

Spotlight and safari suggestions has been fixed and your keystorokes are no longer sent out to apple!

!!!RESTART YOUR COMPUTER NOW TO APPLY CHANGES!!!

---> End Cut & Paste <---

**Comment by karek314** [comment]
`Could not find specified service` will be returned if service has been already disabled or does not exists.

According to
`/System/Library/LaunchAgents/com.apple.parsecd.plist: Operation not permitted while System Integrity Protection is engaged`

It may be good idea to run this script form recovery mode to unload **parsecd**. But i have not tried. i'm simply blocking it's networking with tool like Little Snitch.

**Comment by Hack5190** [comment]
Using "sudo launchctl load -w" followed by "sudo launchctl unload -w" I was able to confirm that the error indicates it had already been disabled.

Like you I use Little Snitch to control outbound traffic and will use it to block parsecd.

Thanks for the quick reply.
