### ISSUE TITLE
Making this work properly on 10.13 (High Sierra)

### ISSUE THREAD

**Issue by ylluminarious** [karek314/macOS-home-call-drop#3]
I've been using this script just fine on 10.12, and I've recently upgraded to a 10.13 beta. I can see that some of the daemons / agents listed in `homecall.sh` are in my `disabled.plist`, but some of them aren't. I assume that this is because some of the daemons / agents have been changed or renamed in 10.13.

**Comment by karek314** [comment]
Hi,
I will take a look on High Sierra as soon i will upgrade.

Leaving that issue open.

**Comment by ylluminarious** [comment]
@karek314 Thanks! I appreciate it, and I'm sure everyone else who uses this does as well.

**Comment by karek314** [comment]
Glad it's useful. Please expect delay with High Sierra, due file system change i'm little bit sceptical with this update, thus i won't jump straight on new releases. To avoid any unnecessary system/data recoveries.

**Comment by ylluminarious** [comment]
@karek314 Sure, no problem.

**Comment by ylluminarious** [comment]
@karek314 Can we expect an update for High Sierra anytime soon? 10.13.2 just recently came out, so the stability issues seem to have gotten better.

**Comment by karek314** [comment]
Actually i did migrated to High Sierra, script still works but needs SIP to be disabled. I did reviewed if there are any other agents or daemons to add to script, seems there is not much added in that matter, while more are protected by sip.

**Comment by ylluminarious** [comment]
@karek314 Ok, thanks for the info. Yeah, it seems to me also that most daemons and agents are the same. I don't use SIP anyway, so I don't have any trouble with it.

So I'll go ahead and close this ticket unless there's anything that you can think of which needs to be changed for High Sierra.

**Comment by karek314** [comment]
After first look it seems it's fine, however if i will find anything i will for sure make PR, not later than end of January 2018. Let's leave it open until end January 2018.

**Comment by ylluminarious** [comment]
@karek314 Alright :+1:

**Comment by ylluminarious** [comment]
I was just thinking about your project and realized we're at the end of January. Are we good or should we still leave this open?

**Comment by karek314** [comment]
Hi, sorry for delay.
In terms of internet connections from/to machine not much changed. Anyway i do recommend software like Little Snitch.

I have added detection to made it clear about SIP change
https://github.com/karek314/macOS-home-call-drop/commit/b3ed669e8448d70b6f984199ac774e2eef164909

**Comment by ylluminarious** [comment]
@karek314 Ok, thanks.
